return {
    custom_hud = {
        en = "Custom HUD",
        ["zh-cn"] = "自定义 HUD",
        ru = "Настраиваемый интерфейс",
        ["zh-tw"] = "自訂 HUD",
        ko = "커스텀 HUD",
    },
    custom_hud_description = {
        en = "Allows custom placement of HUD elements.",
        ["zh-cn"] = "允许自定义排列 HUD 元素。",
        ru = "Позволяет перемещать элементы интерфейса.",
        ["zh-tw"] = "允許自訂排列 HUD 元素。",
        ko = "HUD 창의 위치를 사용자 지정할 수 있습니다.",
    },
    toggle_hud_customization_key = {
        en = "Toggle HUD Customization",
        ["zh-cn"] = "开关 HUD 自定义",
        ru = "Переключение настройки интерфейса",
        ["zh-tw"] = "開關 HUD 自訂",
        ko = "HUD 수정 전환",
    },
    toggle_hud_customization_key_description = {
        en = "Toggles HUD customization on/off.",
        ["zh-cn"] = "切换 HUD 自定义功能的开关。",
        ru = "Включение/отключение оверлея настройки интерфейса.",
        ["zh-tw"] = "切換 HUD 自訂功能的開關。",
        ko = "HUD 수정 기능을 켜거나 끕니다.",
    },
    toggle_hud_hidden_key = {
        en = "Toggle HUD",
        ["zh-cn"] = "开关 HUD",
        ru = "Переключение интерфейса",
        ko = "HUD 전환",
    },
    toggle_hud_hidden_key_description = {
        en = "Toggles the HUD on/off.",
        ["zh-cn"] = "切换 HUD 的开关。",
        ru = "Включение/отключение игрового интерфейса.",
        ["zh-tw"] = "切換 HUD 的開關。",
        ko = "HUD를 켜거나 끕니다.",
    },
    reset_hud = {
        en = "Reset HUD",
        ["zh-cn"] = "重置 HUD",
        ru = "Сброс интерфейса",
        ["zh-tw"] = "重置 HUD",
        ko = "HUD 초기화",
    },
    reset_hud_description = {
        en = "Restore the HUD to Fatshark defaults.",
        ["zh-cn"] = "恢复 HUD 为肥鲨默认值。",
        ru = "Вернуть интерфейс к стандартным настройкам Fatshark.",
        ["zh-tw"] = "將 HUD 還原為預設值。",
        ko = "HUD를 Fatshark 기본값으로 복원합니다.",
    },
    opacity = {
        en = "Opacity Multiplier",
        ["zh-cn"] = "不透明度倍数",
        ru = "Множитель прозрачности",
        ["zh-tw"] = "不透明度倍數",
       ko = "불투명도 비율",
    },
    opacity_description = {
        en = "Adjusts element opacity.",
        ["zh-cn"] = "调整元素不透明度。",
        ru = "Настройте прозрачность элементов.",
        ["zh-tw"] = "調整元素不透明度。",
        ko = "창의 불투명도를 조정합니다.",
    },
    display_grid = {
        en = "Display Grid",
        ["zh-cn"] = "显示网格",
        ru = "Показать сетку",
        ["zh-tw"] = "顯示網格",
        ko = "기준선 표시",
    },
    display_grid_description = {
        en = "Toggles display of a customizable grid to aid in repositioning elements.",
        ["zh-cn"] = "开关用于辅助元素定位的可自定义网格。",
        ru = "Переключение отображения настроечной сетки для облегчения изменения положения элементов.",
        ["zh-tw"] = "切換顯示可自訂網格，以幫助重新定位元素。",
        ko = "창 위치 조정용 기준선 표시 여부를 전환합니다.",
    },
    snap_to_grid = {
        en = "Snap to Grid",
        ["zh-cn"] = "吸附到网格",
        ru = "Привязка к сетке",
        ["zh-tw"] = "吸附到網格",
        ko = "기준선에 맞추기",
    },
    snap_to_grid_description = {
        en = "Toggles snapping of elements to visible grid lines.",
        ["zh-cn"] = "开关是否将元素吸附到网格线上。",
        ru = "Переключение привязки элементов к видимым линиям сетки.",
        ["zh-tw"] = "切換元素是否吸附到可見網格線。",
        ko = "창을 보이는 기준선에 맞출지 설정을 전환합니다.",
    },
    grid_cols = {
        en = "Columns",
        ["zh-cn"] = "列",
        ru = "Столбцы",
        ["zh-tw"] = "列",
        ko = "세로",
    },
    grid_rows = {
        en = "Rows",
        ["zh-cn"] = "行",
        ru = "Ряды",
        ["zh-tw"] = "行",
        ko = "가로",
    }
}
