local mod = get_mod("psych_ward")

mod:add_global_localize_strings({
  loc_toggle_view_buttons = {
    en = "Vendors",
    ["zh-cn"] = "大厅功能",
    ru = "Торговцы",
    ja = "ベンダー",
    ["zh-tw"] = "大廳功能",
    ko = "로비 기능",
  }
})

return {
  psych_ward = {
    en = "Psych Ward",
    ["zh-cn"] = "快捷访问",
    ru = "Психушка",
    ["zh-tw"] = "靈能室",
    ko = "바로가기",
  },
  psych_ward_description = {
    en = "Provides access to many Hub features from the Character Select menu.",
    ["zh-cn"] = "直接在角色选择页面使用各种大厅功能。",
    ru = "Psych Ward - Позволяет войти прямо на стрельбище в Псайканиум, минуя Хаб.",
    ja = "キャラクター選択画面から様々なハブ機能へとアクセスできるようになります。",
    ["zh-tw"] = "啟用直接進入靈能室功能，無需進入大廳。",
    ko = "캐릭터 선택 메뉴에서 로비의 다양한 기능에 접근할 수 있습니다.",
  },
  horde_button = {
    en = "Mortis Trials",
    ["zh-cn"] = "死灵试炼",
    ru = "Испытания Мортис",
    ja = "モーティスの試練",
    ["zh-tw"] = "死神試煉",
    ko = "몰티스 시련",
  },
  mission_button = {
    en = "Mission Board",
    ja = "ミッションボード",
    ["zh-cn"] = "任务面板",
    ru = "Выбор миссий",
    ["zh-tw"] = "任務面板",
    ko = "미션 터미널",
  },
    pw_mission_button_pos_size = {
      en = "Mission Button",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Кнопка Миссии",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_mission_button_pos_h = {
      en = "Horizontal position",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Расположение по горизонтали",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_mission_button_pos_v = {
      en = "Vertical position",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Расположение по вертикали",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_mission_button_size_h = {
      en = "Width",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Ширина",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_mission_button_size_v = {
      en = "Height",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Высота",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
  vendor_button = {
    en = "Armoury",
    ["zh-cn"] = "军械交易所",
    ru = "Оружейная",
    ja = "武器交換",
    ["zh-tw"] = "軍械交易所",
    ko = "무기 교환소",
  },
    pw_vendor_button_pos_size = {
      en = "Armoury Button",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Кнопка Оружейная",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_vendor_button_pos_h = {
      en = "Horizontal position",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Расположение по горизонтали",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_vendor_button_pos_v = {
      en = "Vertical position",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Расположение по вертикали",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_vendor_button_size_h = {
      en = "Width",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Ширина",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_vendor_button_size_v = {
      en = "Height",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Высота",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
  contracts_button = {
    en = "Contracts",
    ["zh-cn"] = "每周协议",
    ru = "Контракты",
    ja = "週間契約",
    ["zh-tw"] = "領主商店",
    ko = "계약",
  },
    pw_contracts_button_pos_size = {
      en = "Contracts Button",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Кнопка Контракты",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_contracts_button_pos_h = {
      en = "Horizontal position",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Расположение по горизонтали",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_contracts_button_pos_v = {
      en = "Vertical position",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Расположение по вертикали",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_contracts_button_size_h = {
      en = "Width",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Ширина",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_contracts_button_size_v = {
      en = "Height",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Высота",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
  crafting_button = {
    en = "Crafting",
    ["zh-cn"] = "锻造",
    ru = "Кузница",
    ja = "クラフト",
    ["zh-tw"] = "鍛造",
    ko = "제작",
  },
    pw_crafting_button_pos_size = {
      en = "Crafting Button",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Кнопка Кузница",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_crafting_button_pos_h = {
      en = "Horizontal position",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Расположение по горизонтали",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_crafting_button_pos_v = {
      en = "Vertical position",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Расположение по вертикали",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_crafting_button_size_h = {
      en = "Width",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Ширина",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_crafting_button_size_v = {
      en = "Height",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Высота",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
  cosmetics_button = {
    en = "Cosmetics",
    ru = "Интендант",
    ["zh-cn"] = "装饰品",
    ja = "装飾品",
    ["zh-tw"] = "雜貨店",
    ko = "장식품",
  },
    pw_cosmetics_button_pos_size = {
      en = "Cosmetics Button",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Кнопка Интендант",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_cosmetics_button_pos_h = {
      en = "Horizontal position",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Расположение по горизонтали",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_cosmetics_button_pos_v = {
      en = "Vertical position",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Расположение по вертикали",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_cosmetics_button_size_h = {
      en = "Width",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Ширина",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_cosmetics_button_size_v = {
      en = "Height",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Высота",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
  penance_button = {
    en = "Penances",
    ru = "Искупления",
    ["zh-cn"] = "苦修",
    ja = "苦行",
    ["zh-tw"] = "苦修",
    ko = "고행",
  },
    pw_penance_button_pos_size = {
      en = "Penances Button",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Кнопка Искупления",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_penance_button_pos_h = {
      en = "Horizontal position",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Расположение по горизонтали",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_penance_button_pos_v = {
      en = "Vertical position",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Расположение по вертикали",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_penance_button_size_h = {
      en = "Width",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Ширина",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_penance_button_size_v = {
      en = "Height",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Высота",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
  inventory_button = {
    en = "Inventory",
    ["zh-cn"] = "库存",
    ru = "Инвентарь",
    ja = "インベントリ",
    ["zh-tw"] = "裝備",
    ko = "인벤토리",
  },
    pw_inventory_button_pos_size = {
      en = "Inventory Button",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Кнопка Инвентарь",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_inventory_button_pos_h = {
      en = "Horizontal position",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Расположение по горизонтали",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_inventory_button_pos_v = {
      en = "Vertical position",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Расположение по вертикали",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_inventory_button_size_h = {
      en = "Width",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Ширина",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
    pw_inventory_button_size_v = {
      en = "Height",
      -- ja = "",
      -- ["zh-cn"] = "",
      ru = "Высота",
     -- ["zh-tw"] = "",
      -- ko = "",
    },
  havoc_button = {
    en = "Havoc Mission",
    ["zh-cn"] = "浩劫任务",
    ja = "ハヴォック任務",
    ["zh-tw"] = "浩劫任務",
    ko = "하복 임무",
  },
  meatgrinder_button = {
    en = "Meat Grinder",
    ["zh-cn"] = "绞肉机",
    ja = "肉挽き機",
    ["zh-tw"] = "絞肉機",
    ko = "사이카니움",
    ru = "Стрельбище",
  },
  exit_text = {
    en = "Press %s to quit",
    ja = "%sで終了",
    ["zh-cn"] = "按下%s以退出",
    ru = "Нажмите %s, чтобы выйти",
    ["zh-tw"] = "按下%s以離開",
    ko = "종료하려면 %s를 누르세요",
  },
  cutscenes_hub_only = {
    en = "Only Viewable from the Hub",
    ["zh-cn"] = "仅可在大厅内查看",
    ru = "Можно посмотреть только в Хабе",
    ja = "ハブでのみ閲覧可能",
    ["zh-tw"] = "僅可在大廳內查看",
    ko = "로비에서만 볼 수 있음",
  },
  enter_hub = {
    en = "Enter Hub",
    ["zh-cn"] = "进入大厅",
    ja = "ハブに行く",
    ["zh-tw"] = "進入大廳",
    ko = "로비로 진입",
    ru = "В Хаб",
  },
  allow_chat_main_menu = {
    en = "Allow Chat in Character Select screen",
    ["zh-cn"] = "允许在角色选择界面使用聊天框",
    ja = "キャラクター選択画面でのチャットを許可",
    ["zh-tw"] = "允許在角色選擇界面使用聊天框",
    ko = "캐릭터 선택 화면에서 채팅 허용",
    ru = "Разрешить Чат на экране выбора персонажей",
  },
}
